[package]
name = "edda"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.29"
meshtastic = "0.1.7"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["macros", "rt", "sync"] }
