[package]
name = "edda"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
meshtastic = "0.1.7"
ratatui = "0.29.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "sync"] }
